#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Shaan Narendran <shaannaren06@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-only

"""Generate web/src/lib/features.ts from observal_cli/features.py.

Run: python scripts/sync_features.py

This ensures the Python and TypeScript feature registries stay in sync.
Enforced by tests/test_features_sync.py in CI.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Add project root to path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from observal_cli.features import FEATURE_VERSIONS

OUTPUT_PATH = ROOT / "web" / "src" / "lib" / "features.ts"

TEMPLATE = '''\
// AUTO-GENERATED by scripts/sync_features.py — DO NOT EDIT MANUALLY
// Source of truth: observal_cli/features.py

/**
 * Maps feature names to the minimum version that supports them.
 * Used for version negotiation: when CLI and server are at different versions,
 * both degrade to min(cli, server) feature set.
 */
export const FEATURE_VERSIONS: Record<string, string> = {{
{entries}
}};

/**
 * Check if a feature is available at the given effective version.
 * effective = min(cli_version, server_version)
 */
export function isFeatureAvailable(feature: string, effectiveVersion: string): boolean {{
  const minVersion = FEATURE_VERSIONS[feature];
  if (!minVersion) return true; // Unknown features assumed available
  return semverGte(effectiveVersion, minVersion);
}}

/**
 * Simple semver >= comparison (major.minor.patch only).
 */
function semverGte(a: string, b: string): boolean {{
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < 3; i++) {{
    const av = pa[i] || 0;
    const bv = pb[i] || 0;
    if (av > bv) return true;
    if (av < bv) return false;
  }}
  return true; // equal
}}
'''


def generate() -> str:
    """Generate TypeScript source from Python FEATURE_VERSIONS."""
    entries = []
    for name, version in sorted(FEATURE_VERSIONS.items()):
        # Convert snake_case to camelCase for TS convention
        camel = _to_camel_case(name)
        entries.append(f'  {camel}: "{version}",')
    return TEMPLATE.format(entries="\n".join(entries))


def _to_camel_case(snake: str) -> str:
    """Convert snake_case to camelCase."""
    parts = snake.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def main() -> None:
    content = generate()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content)
    print(f"✓ Generated {OUTPUT_PATH} ({len(FEATURE_VERSIONS)} features)")


if __name__ == "__main__":
    main()
